---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-github
  namespace: my-reforge-ai
  labels:
    app: mcp-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-github
  template:
    metadata:
      labels:
        app: mcp-github
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: github-server-binary
        image: alpine:3.20
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          set -euo pipefail
          apk add --no-cache curl
          VERSION="v0.18.0"
          ARCHIVE="github-mcp-server_Linux_x86_64.tar.gz"
          URL="https://github.com/github/github-mcp-server/releases/download/${VERSION}/${ARCHIVE}"
          curl -fsSL "${URL}" -o /tmp/github-mcp-server.tar.gz
          tar -xzf /tmp/github-mcp-server.tar.gz -C /tmp
          cp /tmp/github-mcp-server /github-server/github-mcp-server
          chmod +x /github-server/github-mcp-server
        volumeMounts:
        - name: github-server-bin
          mountPath: /github-server
      containers:
      - name: proxy
        image: ghcr.io/sparfenyuk/mcp-proxy:v0.9.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GITHUB_PERSONAL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-mcp-credentials
              key: github-pat
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: http
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          periodSeconds: 30
        command:
        - mcp-proxy
        args:
        - --host=0.0.0.0
        - --port=8080
        - "--allow-origin=*"
        # - "--transport=sse"
        - --pass-environment
        - --
        - /github-server/github-mcp-server
        - stdio
        volumeMounts:
        - name: github-server-bin
          mountPath: /github-server
          readOnly: true
      volumes:
      - name: github-server-bin
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-github
  namespace: my-reforge-ai
  labels:
    app: mcp-github
spec:
  selector:
    app: mcp-github
  ports:
  - name: http
    port: 8080
    targetPort: http
