name: Manual Test Data Push
on:
  workflow_dispatch:

jobs:
  task-picker:
    runs-on: ubuntu-24.04
    outputs:
      task_json: "${{ steps.select_task.outputs.task_json }}"
    steps:
      - name: Checkout my-reforge-ai repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install yarn
        run: npm install -g yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Select eligible task
        id: select_task
        run: |
          TASK_JSON=$(yarn -s ts-node src/task-picker/cli.ts tasks/example-task.yaml)
          echo "task_json=$TASK_JSON" >> $GITHUB_OUTPUT

  push-test-data:
    needs: task-picker
    runs-on: ${{ fromJson(needs.task-picker.outputs.task_json).agent }}
    steps:
      - name: Parse task details
        id: parse_task
        run: |
          TASK_JSON='${{ needs.task-picker.outputs.task_json }}'
          echo "TASK_JSON: $TASK_JSON"
          echo "repo=$(echo "$TASK_JSON" | jq -r '.repo')" >> $GITHUB_OUTPUT
          echo "branch=$(echo "$TASK_JSON" | jq -r '.branch')" >> $GITHUB_OUTPUT
          echo "agent=$(echo "$TASK_JSON" | jq -r '.agent')" >> $GITHUB_OUTPUT

      - name: Clone, commit and push to another repo
        run: |
          GH_TOKEN=$(cat /etc/github/github-pat)
          TARGET_REPO="${{ steps.parse_task.outputs.repo }}"
          TARGET_BRANCH="${{ steps.parse_task.outputs.branch }}"
          REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git"
          
          git clone "$REPO_URL" other-repo
          cd other-repo
          setup-git-workbench --name "github-runner bot" --email spigelly+gh-bot@gmail.com --editor vim

          # Check if the branch exists remotely
          if ! git ls-remote --heads "$REPO_URL" "$TARGET_BRANCH" | grep -q "$TARGET_BRANCH"; then
            echo "Branch '$TARGET_BRANCH' does not exist remotely. Creating it."
            git checkout -b "$TARGET_BRANCH"
            git push -u origin "$TARGET_BRANCH"
          fi

          echo "Branch '$TARGET_BRANCH' exists remotely. Switching to it."
          git switch "$TARGET_BRANCH"

          echo "test data from workflow run ${{ github.run_id }}" > test-data.txt
          git add test-data.txt
          git commit -m "Add test data from workflow"
          git push
