name: Manual Test Data Push
on:
  workflow_dispatch:

jobs:
  task-picker:
    runs-on: ubuntu-24.04
    outputs:
      task_json: "${{ steps.select_task.outputs.task_json }}"
    steps:
      - name: Checkout my-reforge-ai repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install yarn
        run: npm install -g yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Select eligible task
        id: select_task
        run: |
          TASK_JSON=$(yarn -s ts-node src/task-picker/cli.ts tasks/example-task.yaml)
          echo "task_json=$TASK_JSON" >> $GITHUB_OUTPUT

  push-test-data:
    needs: task-picker
    runs-on: ${{ fromJson(needs.task-picker.outputs.task_json).agent }}
    steps:
      - name: Checkout my-reforge-ai repository
        uses: actions/checkout@v3

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Execute task
        run: |
          yarn ts-node src/task-executor/cli.ts src/task-executor/planning-promt-tmpl.md '${{ needs.task-picker.outputs.task_json }}'
          