name: Manual Test Data Push
on:
  workflow_dispatch:

jobs:
  match-task-agent:
    runs-on: ubuntu-24.04
    outputs:
      task_json: '${{ steps.match_agent.outputs.task_json }}'
      agent: '${{ steps.match_agent.outputs.agent }}'
    steps:
      - name: Checkout my-reforge-ai repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install yarn
        run: npm install -g yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Match agent to task
        id: match_agent
        run: |
          ./dist/task-agent-matcher/matcher.js --output-file task.json tasks/example-task.yaml
          TASK_JSON=$(cat task.json | jq -c '.task')
          AGENT=$(cat task.json | jq -r '.agent')
          echo "task_json=$TASK_JSON" >> $GITHUB_OUTPUT
          echo "agent=$AGENT" >> $GITHUB_OUTPUT

  execute-task:
    needs: match-task-agent
    runs-on: ${{ needs.match-task-agent.outputs.agent }}
    steps:
      - name: Checkout my-reforge-ai repository
        uses: actions/checkout@v3

      - name: Build
        run: yarn build

      - name: Execute task
        run: |
          npx ts-node src/task-executor/executor.ts src/task-executor/planning-promt-tmpl.md '${{ needs.match-task-agent.outputs.task_json }}'